workflows: 

   android-kmm-workflow: 

     name: Android KMM Workflow 

     max_build_duration: 120 

     instance_type: mac_pro 

     environment:
       java: 1.8
    scripts:

      - name: Build Android debug APK

        working_directory: android

        script: ./gradlew assembleRelease

    artifacts:

      - app/build/outputs/**/**/*.apk
