workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 60
    environment:
       
      xcode: latest
      cocoapods: default
    artifacts:
      - build/android/spy.apk
    publishing:
      email:
        recipients:
          - Arshkhan1.ak@gmail.com
